version: "3"

services:
  registry:
    build:
      dockerfile: Dockerfile
      context: ./registry
    restart: always
    container_name: registry
    hostname: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry